[tool.black]
line-length = 88
target-version = ["py311"]

[tool.mypy]
python_version = "3.11"
strict = true
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.flake8]
max-line-length = 88
exclude = [
    ".venv",
    "__pycache__",
    "migrations",
    "tests",
]
ignore = [
    "E203",  # конфликт с black
    "W503",  # конфликт с black
    "E501",  # длина строки, пусть форматирует black
]

[tool.pytest.ini_options]
addopts = "-v --tb=short"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["tests"]
python_files = ["test_*.py"]
pythonpath = ["."]